version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password

  frontend:
    build:
      context: ./frontend
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "yarn serve"
    depends_on:
      - backend

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
