version: "3.9"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./frontend
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
    command: /bin/sh -c "yarn serve"

  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
