name: MiniFlix CI

on:
  push:
    branches: [ actions-workflow ]
  pull_request:
    branches: [ actions-workflow ]

defaults:
  run:
    working-directory: ./backend

rails-env: &rails-env
  DB_HOST: postgres
  DB_USERNAME: postgres
  DB_PASSWORD: password
  DB_PORT: ${{ job.services.postgres.ports[5432] }}
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/markkampstra/miniflix_backend:1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    strategy:
      matrix:
        ruby-version: ['3.0']

    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Check working-directory
      run: pwd
      working-directory: ${{env.working-directory}}
    - name: Setup bundle
      run: bundle install
    - name: Setup DB for tests
      env:
        <<: *rails-env
        # DB_HOST: postgres
        # DB_USERNAME: postgres
        # DB_PASSWORD: password
        # DB_PORT: ${{ job.services.postgres.ports[5432] }}
        # RAILS_ENV: test
      run: bundle exec rails db:create
    - name: Run tests
      env:
        DB_HOST: postgres
        DB_USERNAME: postgres
        DB_PASSWORD: password
        DB_PORT: ${{ job.services.postgres.ports[5432] }}
      run: bundle exec rspec
