name: Self hosted runner test

on:
  push:
    branches: [ actions-workflow ]
  pull_request:
    branches: [ actions-workflow ]

env:
  BUNDLE_PATH: ./vendor/bundle
  BUNDLE_JOBS: 2
  BUNDLE_RETRY: 3
  ImageOS: ubuntu18

jobs:
  run-ci:
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Ruby gem cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

